controller_joint_names: ['', 'br_Joint', 'bl_Joint', 'fl_Joint', 'fr_Joint', 'yuntai_Joint', ]
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: yuntai_Joint
  pid: {p: 0.05, i: 0.01, d: 0.5}
