scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser
    min_x: -0.434
    max_x: 0.434
    min_y: -0.448
    max_y: 0.448
    min_z: -0.2
    max_z: 0.2