scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser
    min_x: -0.334
    max_x: 0.334
    min_y: -0.248
    max_y: 0.248
    min_z: -0.2
    max_z: 0.2